<?php

namespace Database\Seeders;

use App\Models\Campaign;
use App\Models\ContractType;
use App\Models\Department;
use App\Models\Employee;
use App\Models\ScheduleType;
use App\Models\Team;
use App\Models\TierLevel;
use App\Models\User;
use App\Models\WorkRole;
use App\Models\WorkScheduleTemplate;
use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $employees = [
            [
                'name' => 'Supervisor Demo',
                'user_email' => 'supervisor@dosys.local',
                'campaign' => 'PALMETTO',
                'team' => 'BDC',
                'department' => 'OPERATIONS',
                'work_role' => 'SUPERVISOR',
                'tier' => 'Tier 6',
                'schedule_type' => 'Diurna',
                'schedule_template' => 'Diurna 40h - 5 días x 8h',
                'contract_type' => 'Permanente',
                'weekly_hours' => 40,
                'ordinary_weekly_hours' => 40,
                'daily_hours' => 8,
                'calendar_days' => 30,
                'overtime_hours' => 0,
                'preassigned_overtime_period_hours' => 0,
                'monthly_salary' => 20500,
                'semi_monthly_salary' => 10250,
                'daily_rate' => 683.3333,
                'hourly_rate' => 85.40,
                'overtime_hourly_rate' => 106.75,
                'salary_calculation_method' => 'semi_monthly_fixed_with_deductions',
                'location' => 'on_site',
                'applies_private_insurance' => false,
                'applies_ihss' => true,
                'applies_isr' => false,
                'applies_rap' => false,
            ],
            [
                'name' => 'Empleado Diurno 40h Demo',
                'campaign' => 'PALMETTO',
                'team' => 'BDC',
                'department' => 'OPERATIONS',
                'work_role' => 'DEBT COLLECTOR',
                'tier' => 'Tier 2',
                'schedule_type' => 'Diurna',
                'schedule_template' => 'Diurna 40h - 5 días x 8h',
                'contract_type' => 'Permanente',
                'weekly_hours' => 40,
                'ordinary_weekly_hours' => 40,
                'daily_hours' => 8,
                'calendar_days' => 30,
                'overtime_hours' => 5,
                'preassigned_overtime_period_hours' => 10,
                'monthly_salary' => 15000,
                'semi_monthly_salary' => 7500,
                'daily_rate' => 500,
                'hourly_rate' => 62.50,
                'overtime_hourly_rate' => 78.13,
                'salary_calculation_method' => 'semi_monthly_fixed_with_deductions',
                'location' => 'on_site',
                'applies_private_insurance' => false,
                'applies_ihss' => true,
                'applies_isr' => false,
                'applies_rap' => false,
            ],
            [
                'name' => 'Empleado Diurno 36h Demo',
                'campaign' => 'PALMETTO',
                'team' => 'BDC',
                'department' => 'OPERATIONS',
                'work_role' => 'DEBT COLLECTOR',
                'tier' => 'Tier 2',
                'schedule_type' => 'Diurna',
                'schedule_template' => 'Diurna 36h - 4 días 7h + 1 día 8h',
                'contract_type' => 'Permanente',
                'weekly_hours' => 36,
                'ordinary_weekly_hours' => 36,
                'daily_hours' => 0,
                'calendar_days' => 30,
                'overtime_hours' => 0,
                'preassigned_overtime_period_hours' => 0,
                'monthly_salary' => 14200,
                'semi_monthly_salary' => 7100,
                'daily_rate' => 473.3333,
                'hourly_rate' => 65.7407,
                'overtime_hourly_rate' => 82.1759,
                'salary_calculation_method' => 'scheduled_shift_prorated',
                'location' => 'on_site',
                'applies_private_insurance' => false,
                'applies_ihss' => true,
                'applies_isr' => false,
                'applies_rap' => false,
            ],
            [
                'name' => 'Empleado Rotativo Elalf Demo',
                'campaign' => 'PALMETTO',
                'team' => 'BDC',
                'department' => 'OPERATIONS',
                'work_role' => 'DEBT COLLECTOR',
                'tier' => 'Tier 2',
                'schedule_type' => 'Rotativa',
                'schedule_template' => 'Rotativa 4x4',
                'contract_type' => 'Permanente',
                'weekly_hours' => 44,
                'ordinary_weekly_hours' => 44,
                'daily_hours' => 11,
                'calendar_days' => 30,
                'overtime_hours' => 4,
                'preassigned_overtime_period_hours' => 8,
                'monthly_salary' => 14200,
                'semi_monthly_salary' => 7100,
                'daily_rate' => 473.3333,
                'hourly_rate' => 59.20,
                'overtime_hourly_rate' => 74,
                'salary_calculation_method' => 'semi_monthly_fixed_with_deductions',
                'schedule_cycle_anchor_date' => '2026-05-25',
                'rotation_work_days' => 4,
                'rotation_rest_days' => 4,
                'hubstaff_expected_hours_per_workday' => 11,
                'paid_hours_per_workday' => 12,
                'paid_lunch_minutes_per_workday' => 60,
                'lunch_included_in_hubstaff_total' => false,
                'breaks_included_in_hubstaff_total' => true,
                'location' => 'on_site',
                'applies_private_insurance' => false,
                'applies_ihss' => true,
                'applies_isr' => false,
                'applies_rap' => false,
            ],
            [
                'name' => 'Empleado Rotativo Salario Distinto Demo',
                'campaign' => 'PALMETTO',
                'team' => 'BDC',
                'department' => 'OPERATIONS',
                'work_role' => 'DEBT COLLECTOR',
                'tier' => 'Tier 2',
                'schedule_type' => 'Rotativa',
                'schedule_template' => 'Rotativa 4x4',
                'contract_type' => 'Permanente',
                'weekly_hours' => 44,
                'ordinary_weekly_hours' => 44,
                'daily_hours' => 11,
                'calendar_days' => 30,
                'overtime_hours' => 4,
                'preassigned_overtime_period_hours' => 8,
                'monthly_salary' => 16500,
                'semi_monthly_salary' => 8250,
                'daily_rate' => 550,
                'hourly_rate' => 68.75,
                'overtime_hourly_rate' => 85.9375,
                'salary_calculation_method' => 'semi_monthly_fixed_with_deductions',
                'schedule_cycle_anchor_date' => '2026-05-25',
                'rotation_work_days' => 4,
                'rotation_rest_days' => 4,
                'hubstaff_expected_hours_per_workday' => 11,
                'paid_hours_per_workday' => 12,
                'paid_lunch_minutes_per_workday' => 60,
                'lunch_included_in_hubstaff_total' => false,
                'breaks_included_in_hubstaff_total' => true,
                'location' => 'on_site',
                'applies_private_insurance' => false,
                'applies_ihss' => true,
                'applies_isr' => false,
                'applies_rap' => false,
            ],
            [
                'name' => 'Empleado Nocturno Demo',
                'campaign' => 'PALMETTO',
                'team' => 'BDC',
                'department' => 'OPERATIONS',
                'work_role' => 'DEBT COLLECTOR',
                'tier' => 'Tier 2',
                'schedule_type' => 'Nocturna',
                'schedule_template' => 'Nocturna personalizada',
                'contract_type' => 'Permanente',
                'weekly_hours' => 40,
                'ordinary_weekly_hours' => 40,
                'daily_hours' => 8,
                'calendar_days' => 30,
                'overtime_hours' => 0,
                'preassigned_overtime_period_hours' => 0,
                'monthly_salary' => 16000,
                'semi_monthly_salary' => 8000,
                'daily_rate' => 533.3333,
                'hourly_rate' => 66.6667,
                'overtime_hourly_rate' => 83.3334,
                'salary_calculation_method' => 'semi_monthly_fixed_with_deductions',
                'location' => 'on_site',
                'applies_private_insurance' => false,
                'applies_ihss' => true,
                'applies_isr' => false,
                'applies_rap' => false,
            ],
        ];

        $supervisorId = User::query()->where('email', 'supervisor@dosys.local')->value('id');

        foreach ($employees as $row) {
            $employee = Employee::query()->updateOrCreate(['name' => $row['name']], [
                'campaign_id' => Campaign::query()->where('name', $row['campaign'])->value('id'),
                'team_id' => Team::query()->where('name', $row['team'])->value('id'),
                'department_id' => Department::query()->where('name', $row['department'])->value('id'),
                'work_role_id' => WorkRole::query()->where('name', $row['work_role'])->value('id'),
                'tier_level_id' => TierLevel::query()->where('name', $row['tier'])->value('id'),
                'schedule_type_id' => ScheduleType::query()->where('name', $row['schedule_type'])->value('id'),
                'work_schedule_template_id' => WorkScheduleTemplate::query()->where('name', $row['schedule_template'])->value('id'),
                'contract_type_id' => ContractType::query()->where('name', $row['contract_type'])->value('id'),
                'supervisor_user_id' => empty($row['user_email']) ? $supervisorId : null,
                'schedule_type_name_snapshot' => $row['schedule_type'],
                'weekly_hours' => $row['weekly_hours'],
                'ordinary_weekly_hours' => $row['ordinary_weekly_hours'],
                'daily_hours' => $row['daily_hours'],
                'calendar_days' => $row['calendar_days'],
                'overtime_hours' => $row['overtime_hours'] ?? 0,
                'preassigned_overtime_weekly_hours' => $row['overtime_hours'] ?? 0,
                'preassigned_overtime_period_hours' => $row['preassigned_overtime_period_hours'] ?? 0,
                'monthly_salary' => $row['monthly_salary'],
                'semi_monthly_salary' => $row['semi_monthly_salary'],
                'daily_rate' => $row['daily_rate'],
                'hourly_rate' => $row['hourly_rate'],
                'overtime_hourly_rate' => $row['overtime_hourly_rate'] ?? 0,
                'salary_calculation_method' => $row['salary_calculation_method'],
                'salary_values_are_manual' => true,
                'schedule_cycle_anchor_date' => $row['schedule_cycle_anchor_date'] ?? null,
                'rotation_work_days' => $row['rotation_work_days'] ?? null,
                'rotation_rest_days' => $row['rotation_rest_days'] ?? null,
                'hubstaff_expected_hours_per_workday' => $row['hubstaff_expected_hours_per_workday'] ?? null,
                'paid_hours_per_workday' => $row['paid_hours_per_workday'] ?? null,
                'paid_lunch_minutes_per_workday' => $row['paid_lunch_minutes_per_workday'] ?? 0,
                'lunch_included_in_hubstaff_total' => $row['lunch_included_in_hubstaff_total'] ?? true,
                'breaks_included_in_hubstaff_total' => $row['breaks_included_in_hubstaff_total'] ?? true,
                'location' => $row['location'],
                'applies_private_insurance' => $row['applies_private_insurance'],
                'applies_ihss' => $row['applies_ihss'],
                'applies_isr' => $row['applies_isr'],
                'applies_rap' => $row['applies_rap'],
                'active' => true,
            ]);

            if (! empty($row['user_email'])) {
                User::query()
                    ->where('email', $row['user_email'])
                    ->update(['employee_id' => $employee->id]);
            }
        }
    }
}
